project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left: 
      - icon: pencil-square
        text: "Hands-on Exercise 1"
        menu:
          - text: "Hands-on Part 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3 Part I"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_1.html"
          - text: "Hands-on Exercise 3 Part II"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.html"
          - text: "Hands-on Exercise 4 Part I"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_1.html"
          - text: "Hands-on Exercise 4 Part II"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_2.html"
          - text: "Hands-on Exercise 4 Part III"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_3.html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Exercise 7"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
      - icon: pencil-square
        text: "Hands-on Part 2"
        menu:
          - text: "Hands-on Exercise 8 Part I"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_1.html"
          - text: "Hands-on Exercise 8 Part II"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_2.html"
          - text: "Hands-on Exercise 8 Part III"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_3.html"
          - text: "Hands-on Exercise 9 Part I"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09_1.html"
          - text: "Hands-on Exercise 9 Part II"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09_2.html"
          - text: "Hands-on Exercise 9 Part III"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09_3.html"
          - text: "Hands-on Exercise 9 Part IV"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09_4.html"
          - text: "Hands-on Exercise 9 Part V"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09_5.html"
      - icon: book-half
        text: "In-class"
        menu:
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "In-class Exercise 5"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
          - text: "In-class Exercise 6"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
          - text: "In-class Exercise 9"
            href: "In-class_Ex/In-class_Ex09/In-class_Ex09.html"
          - text: "In-class Exercise 10"
            href: "In-class_Ex/In-class_Ex10/In-class_Ex10.html"
      - icon: person-fill
        text: "Take-home"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 1 (Geographical Distribution)"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01_geo.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
      - icon: user-fill
        text: "Group Project"
        href: "https://isss608-g2.netlify.app/"

    right:
      - href: about.qmd
        text: About
    
    tools:
      - icon: linkedin         
        href: https://www.linkedin.com/in/lnealicia/
      - icon: github         
        href: https://github.com/lnealicia/
      - icon: bar-chart-fill
        href: https://public.tableau.com/app/profile/lne.alicia/vizzes

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
