project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3 Part I"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_1.html"
          - text: "Hands-on Exercise 3 Part II"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.html"
          - text: "Hands-on Exercise 4 Part I"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_1.html"
          - text: "Hands-on Exercise 4 Part II"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_2.html"
          - text: "Hands-on Exercise 4 Part III"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_3.html"
          - text: "Hands-on Exercise 4 Part IV"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_4.html"


      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"

      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 1 (Geographical Distribution)"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01_geo.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"

    right:
      - href: about.qmd
        text: About
    
    tools:       
    - icon: linkedin         
      href: https://www.linkedin.com/in/lnealicia/       
    - icon: github         
      href: https://github.com/lnealicia/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

